# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/",
        "doc_host": "",
        "git_url": "https://github.com/majorgilles/build-a-text-to-image-generator-from-scratch-companion",
        "lib_path": "build_a_text_to_image_generator_from_scratch_companion",
    },
    "syms": {
        "build_a_text_to_image_generator_from_scratch_companion.utils.bpe": {
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.BPEPart": (
                "utils/bpe.html#bpepart",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.BPETokenizer": (
                "utils/bpe.html#bpetokenizer",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.BPETokenizer.__call__": (
                "utils/bpe.html#bpetokenizer.__call__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.BPETokenizer.__init__": (
                "utils/bpe.html#bpetokenizer.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.BPETokenizer.decode": (
                "utils/bpe.html#bpetokenizer.decode",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.BPEWork": (
                "utils/bpe.html#bpework",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.Encoder": (
                "utils/bpe.html#encoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.Encoder.__init__": (
                "utils/bpe.html#encoder.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.Encoder.bpe": (
                "utils/bpe.html#encoder.bpe",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.Encoder.decode": (
                "utils/bpe.html#encoder.decode",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.Encoder.encode": (
                "utils/bpe.html#encoder.encode",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.Encoder.encode_and_show_work": (
                "utils/bpe.html#encoder.encode_and_show_work",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.bytes_to_unicode": (
                "utils/bpe.html#bytes_to_unicode",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.get_encoder": (
                "utils/bpe.html#get_encoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.get_file": (
                "utils/bpe.html#get_file",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.bpe.get_pairs": (
                "utils/bpe.html#get_pairs",
                "build_a_text_to_image_generator_from_scratch_companion/utils/bpe.py",
            ),
        },
        "build_a_text_to_image_generator_from_scratch_companion.utils.captioning": {
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.AttentionBlock": (
                "utils/captioning.html#attentionblock",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.AttentionBlock.__init__": (
                "utils/captioning.html#attentionblock.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.AttentionBlock.forward": (
                "utils/captioning.html#attentionblock.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.Decoder": (
                "utils/captioning.html#decoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.Decoder.__init__": (
                "utils/captioning.html#decoder.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.Decoder.forward": (
                "utils/captioning.html#decoder.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.FlickrCaptionDataset": (
                "utils/captioning.html#flickrcaptiondataset",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.FlickrCaptionDataset.__getitem__": (
                "utils/captioning.html#flickrcaptiondataset.__getitem__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.FlickrCaptionDataset.__init__": (
                "utils/captioning.html#flickrcaptiondataset.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.FlickrCaptionDataset.__len__": (
                "utils/captioning.html#flickrcaptiondataset.__len__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.FlickrCaptionDataset._construct_image_transform": (
                "utils/captioning.html#flickrcaptiondataset._construct_image_transform",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.FlickrCaptionDataset._create_input_label_mappings": (
                "utils/captioning.html#flickrcaptiondataset._create_input_label_mappings",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.FlickrCaptionDataset._group_captions": (
                "utils/captioning.html#flickrcaptiondataset._group_captions",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.FlickrCaptionDataset._load_and_prepare_image": (
                "utils/captioning.html#flickrcaptiondataset._load_and_prepare_image",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.FlickrCaptionDataset._load_and_process_images": (
                "utils/captioning.html#flickrcaptiondataset._load_and_process_images",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.SinusoidalPosEmb": (
                "utils/captioning.html#sinusoidalposemb",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.SinusoidalPosEmb.__init__": (
                "utils/captioning.html#sinusoidalposemb.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.SinusoidalPosEmb.forward": (
                "utils/captioning.html#sinusoidalposemb.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.TransformerBlock": (
                "utils/captioning.html#transformerblock",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.TransformerBlock.__init__": (
                "utils/captioning.html#transformerblock.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.TransformerBlock.forward": (
                "utils/captioning.html#transformerblock.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.VisionEncoder": (
                "utils/captioning.html#visionencoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.VisionEncoder.__init__": (
                "utils/captioning.html#visionencoder.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.VisionEncoder.forward": (
                "utils/captioning.html#visionencoder.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.VisionEncoderDecoder": (
                "utils/captioning.html#visionencoderdecoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.VisionEncoderDecoder.__init__": (
                "utils/captioning.html#visionencoderdecoder.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.VisionEncoderDecoder.forward": (
                "utils/captioning.html#visionencoderdecoder.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.center_crop": (
                "utils/captioning.html#center_crop",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.captioning.extract_patches": (
                "utils/captioning.html#extract_patches",
                "build_a_text_to_image_generator_from_scratch_companion/utils/captioning.py",
            ),
        },
        "build_a_text_to_image_generator_from_scratch_companion.utils.clip": {
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.AvgMeter": (
                "utils/clip.html#avgmeter",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.AvgMeter.__init__": (
                "utils/clip.html#avgmeter.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.AvgMeter.__repr__": (
                "utils/clip.html#avgmeter.__repr__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.AvgMeter.reset": (
                "utils/clip.html#avgmeter.reset",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.AvgMeter.update": (
                "utils/clip.html#avgmeter.update",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.CFG": (
                "utils/clip.html#cfg",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.CLIPDataset": (
                "utils/clip.html#clipdataset",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.CLIPDataset.__getitem__": (
                "utils/clip.html#clipdataset.__getitem__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.CLIPDataset.__init__": (
                "utils/clip.html#clipdataset.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.CLIPDataset.__len__": (
                "utils/clip.html#clipdataset.__len__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.CLIPModel": (
                "utils/clip.html#clipmodel",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.CLIPModel.__init__": (
                "utils/clip.html#clipmodel.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.CLIPModel.forward": (
                "utils/clip.html#clipmodel.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.ImageEncoder": (
                "utils/clip.html#imageencoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.ImageEncoder.__init__": (
                "utils/clip.html#imageencoder.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.ImageEncoder.forward": (
                "utils/clip.html#imageencoder.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.ImageTransformLike": (
                "utils/clip.html#imagetransformlike",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.ImageTransformLike.__call__": (
                "utils/clip.html#imagetransformlike.__call__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.ProjectionHead": (
                "utils/clip.html#projectionhead",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.ProjectionHead.__init__": (
                "utils/clip.html#projectionhead.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.ProjectionHead.forward": (
                "utils/clip.html#projectionhead.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.TextEncoder": (
                "utils/clip.html#textencoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.TextEncoder.__init__": (
                "utils/clip.html#textencoder.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.TextEncoder.forward": (
                "utils/clip.html#textencoder.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.TokenizerLike": (
                "utils/clip.html#tokenizerlike",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.TokenizerLike.__call__": (
                "utils/clip.html#tokenizerlike.__call__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.cross_entropy": (
                "utils/clip.html#cross_entropy",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.get_lr": (
                "utils/clip.html#get_lr",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.clip.get_transforms": (
                "utils/clip.html#get_transforms",
                "build_a_text_to_image_generator_from_scratch_companion/utils/clip.py",
            ),
        },
        "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion": {
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.ConditionalUNet": (
                "utils/conditional_diffusion.html#conditionalunet",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.ConditionalUNet.__init__": (
                "utils/conditional_diffusion.html#conditionalunet.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.ConditionalUNet.forward": (
                "utils/conditional_diffusion.html#conditionalunet.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.DDPM": (
                "utils/conditional_diffusion.html#ddpm",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.DDPM.__init__": (
                "utils/conditional_diffusion.html#ddpm.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.DDPM.forward": (
                "utils/conditional_diffusion.html#ddpm.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.EmbedLayer": (
                "utils/conditional_diffusion.html#embedlayer",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.EmbedLayer.__init__": (
                "utils/conditional_diffusion.html#embedlayer.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.EmbedLayer.forward": (
                "utils/conditional_diffusion.html#embedlayer.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.ResidualConvBlock": (
                "utils/conditional_diffusion.html#residualconvblock",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.ResidualConvBlock.__init__": (
                "utils/conditional_diffusion.html#residualconvblock.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.ResidualConvBlock.forward": (
                "utils/conditional_diffusion.html#residualconvblock.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.UnetDown": (
                "utils/conditional_diffusion.html#unetdown",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.UnetDown.__init__": (
                "utils/conditional_diffusion.html#unetdown.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.UnetDown.forward": (
                "utils/conditional_diffusion.html#unetdown.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.UnetUp": (
                "utils/conditional_diffusion.html#unetup",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.UnetUp.__init__": (
                "utils/conditional_diffusion.html#unetup.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.UnetUp.forward": (
                "utils/conditional_diffusion.html#unetup.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.noise_scheduler": (
                "utils/conditional_diffusion.html#noise_scheduler",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.conditional_diffusion.sample": (
                "utils/conditional_diffusion.html#sample",
                "build_a_text_to_image_generator_from_scratch_companion/utils/conditional_diffusion.py",
            ),
        },
        "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion": {
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.Attention": (
                "utils/diffusion.html#attention",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.Attention.__init__": (
                "utils/diffusion.html#attention.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.Attention.forward": (
                "utils/diffusion.html#attention.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.CustomDataset": (
                "utils/diffusion.html#customdataset",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.CustomDataset.__getitem__": (
                "utils/diffusion.html#customdataset.__getitem__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.CustomDataset.__init__": (
                "utils/diffusion.html#customdataset.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.CustomDataset.__len__": (
                "utils/diffusion.html#customdataset.__len__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.DDIMScheduler": (
                "utils/diffusion.html#ddimscheduler",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.DDIMScheduler.__init__": (
                "utils/diffusion.html#ddimscheduler.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.DDIMScheduler.__len__": (
                "utils/diffusion.html#ddimscheduler.__len__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.DDIMScheduler._get_variance": (
                "utils/diffusion.html#ddimscheduler._get_variance",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.DDIMScheduler.add_noise": (
                "utils/diffusion.html#ddimscheduler.add_noise",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.DDIMScheduler.generate": (
                "utils/diffusion.html#ddimscheduler.generate",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.DDIMScheduler.interpolate": (
                "utils/diffusion.html#ddimscheduler.interpolate",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.DDIMScheduler.set_timesteps": (
                "utils/diffusion.html#ddimscheduler.set_timesteps",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.DDIMScheduler.step": (
                "utils/diffusion.html#ddimscheduler.step",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.LayerNorm": (
                "utils/diffusion.html#layernorm",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.LayerNorm.__init__": (
                "utils/diffusion.html#layernorm.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.LayerNorm.forward": (
                "utils/diffusion.html#layernorm.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.PreNorm": (
                "utils/diffusion.html#prenorm",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.PreNorm.__init__": (
                "utils/diffusion.html#prenorm.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.PreNorm.forward": (
                "utils/diffusion.html#prenorm.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.Residual": (
                "utils/diffusion.html#residual",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.Residual.__init__": (
                "utils/diffusion.html#residual.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.Residual.forward": (
                "utils/diffusion.html#residual.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.ResidualBlock": (
                "utils/diffusion.html#residualblock",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.ResidualBlock.__init__": (
                "utils/diffusion.html#residualblock.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.ResidualBlock.forward": (
                "utils/diffusion.html#residualblock.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.TabularImageData": (
                "utils/diffusion.html#tabularimagedata",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.TabularImageData.iterrows": (
                "utils/diffusion.html#tabularimagedata.iterrows",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.UNet": (
                "utils/diffusion.html#unet",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.UNet.__init__": (
                "utils/diffusion.html#unet.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.UNet.forward": (
                "utils/diffusion.html#unet.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.clip": (
                "utils/diffusion.html#clip",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.cosine_beta_schedule": (
                "utils/diffusion.html#cosine_beta_schedule",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.get_attn_layer": (
                "utils/diffusion.html#get_attn_layer",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.get_downsample_layer": (
                "utils/diffusion.html#get_downsample_layer",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.get_upsample_layer": (
                "utils/diffusion.html#get_upsample_layer",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.match_shape": (
                "utils/diffusion.html#match_shape",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.normalize_to_neg_one_to_one": (
                "utils/diffusion.html#normalize_to_neg_one_to_one",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.numpy_to_pil": (
                "utils/diffusion.html#numpy_to_pil",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.plot_losses": (
                "utils/diffusion.html#plot_losses",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.save_images": (
                "utils/diffusion.html#save_images",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.sinusoidal_embedding": (
                "utils/diffusion.html#sinusoidal_embedding",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.transforms": (
                "utils/diffusion.html#transforms",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.diffusion.unnormalize_to_zero_to_one": (
                "utils/diffusion.html#unnormalize_to_zero_to_one",
                "build_a_text_to_image_generator_from_scratch_companion/utils/diffusion.py",
            ),
        },
        "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2": {
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.Block": (
                "utils/gpt2.html#block",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.Block.__init__": (
                "utils/gpt2.html#block.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.Block._feed_forward": (
                "utils/gpt2.html#block._feed_forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.Block.forward": (
                "utils/gpt2.html#block.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.CausalSelfAttention": (
                "utils/gpt2.html#causalselfattention",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.CausalSelfAttention.__init__": (
                "utils/gpt2.html#causalselfattention.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.CausalSelfAttention.forward": (
                "utils/gpt2.html#causalselfattention.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.GPT": (
                "utils/gpt2.html#gpt",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.GPT.__init__": (
                "utils/gpt2.html#gpt.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.GPT.forward": (
                "utils/gpt2.html#gpt.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.GPTConfig": (
                "utils/gpt2.html#gptconfig",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.NewGELU": (
                "utils/gpt2.html#newgelu",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.gpt2.NewGELU.forward": (
                "utils/gpt2.html#newgelu.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/gpt2.py",
            ),
        },
        "build_a_text_to_image_generator_from_scratch_companion.utils.transformer": {
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Batch": (
                "utils/transformer.html#batch",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Batch.__init__": (
                "utils/transformer.html#batch.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Decoder": (
                "utils/transformer.html#decoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Decoder.__init__": (
                "utils/transformer.html#decoder.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Decoder.forward": (
                "utils/transformer.html#decoder.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.DecoderLayer": (
                "utils/transformer.html#decoderlayer",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.DecoderLayer.__init__": (
                "utils/transformer.html#decoderlayer.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.DecoderLayer.forward": (
                "utils/transformer.html#decoderlayer.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Embeddings": (
                "utils/transformer.html#embeddings",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Embeddings.__init__": (
                "utils/transformer.html#embeddings.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Embeddings.forward": (
                "utils/transformer.html#embeddings.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Encoder": (
                "utils/transformer.html#encoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Encoder.__init__": (
                "utils/transformer.html#encoder.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Encoder.forward": (
                "utils/transformer.html#encoder.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.EncoderLayer": (
                "utils/transformer.html#encoderlayer",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.EncoderLayer.__init__": (
                "utils/transformer.html#encoderlayer.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.EncoderLayer.forward": (
                "utils/transformer.html#encoderlayer.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Generator": (
                "utils/transformer.html#generator",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Generator.__init__": (
                "utils/transformer.html#generator.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Generator.forward": (
                "utils/transformer.html#generator.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.LabelSmoothing": (
                "utils/transformer.html#labelsmoothing",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.LabelSmoothing.__init__": (
                "utils/transformer.html#labelsmoothing.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.LabelSmoothing.forward": (
                "utils/transformer.html#labelsmoothing.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.LayerNorm": (
                "utils/transformer.html#layernorm",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.LayerNorm.__init__": (
                "utils/transformer.html#layernorm.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.LayerNorm.forward": (
                "utils/transformer.html#layernorm.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.MultiHeadedAttention": (
                "utils/transformer.html#multiheadedattention",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.MultiHeadedAttention.__init__": (
                "utils/transformer.html#multiheadedattention.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.MultiHeadedAttention.forward": (
                "utils/transformer.html#multiheadedattention.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.NoamOpt": (
                "utils/transformer.html#noamopt",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.NoamOpt.__init__": (
                "utils/transformer.html#noamopt.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.NoamOpt.rate": (
                "utils/transformer.html#noamopt.rate",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.NoamOpt.step": (
                "utils/transformer.html#noamopt.step",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.OptimizerSchedule": (
                "utils/transformer.html#optimizerschedule",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.OptimizerSchedule.step": (
                "utils/transformer.html#optimizerschedule.step",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.PositionalEncoding": (
                "utils/transformer.html#positionalencoding",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.PositionalEncoding.__init__": (
                "utils/transformer.html#positionalencoding.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.PositionalEncoding.forward": (
                "utils/transformer.html#positionalencoding.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.PositionwiseFeedForward": (
                "utils/transformer.html#positionwisefeedforward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.PositionwiseFeedForward.__init__": (
                "utils/transformer.html#positionwisefeedforward.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.PositionwiseFeedForward.forward": (
                "utils/transformer.html#positionwisefeedforward.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.SimpleLossCompute": (
                "utils/transformer.html#simplelosscompute",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.SimpleLossCompute.__call__": (
                "utils/transformer.html#simplelosscompute.__call__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.SimpleLossCompute.__init__": (
                "utils/transformer.html#simplelosscompute.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.SublayerConnection": (
                "utils/transformer.html#sublayerconnection",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.SublayerConnection.__init__": (
                "utils/transformer.html#sublayerconnection.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.SublayerConnection.forward": (
                "utils/transformer.html#sublayerconnection.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Transformer": (
                "utils/transformer.html#transformer",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Transformer.__init__": (
                "utils/transformer.html#transformer.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Transformer.decode": (
                "utils/transformer.html#transformer.decode",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Transformer.encode": (
                "utils/transformer.html#transformer.encode",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.Transformer.forward": (
                "utils/transformer.html#transformer.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.attention": (
                "utils/transformer.html#attention",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.create_model": (
                "utils/transformer.html#create_model",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.make_std_mask": (
                "utils/transformer.html#make_std_mask",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.transformer.subsequent_mask": (
                "utils/transformer.html#subsequent_mask",
                "build_a_text_to_image_generator_from_scratch_companion/utils/transformer.py",
            ),
        },
        "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer": {
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.AttentionHead": (
                "utils/vision_transformer.html#attentionhead",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.AttentionHead.__init__": (
                "utils/vision_transformer.html#attentionhead.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.AttentionHead.forward": (
                "utils/vision_transformer.html#attentionhead.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.Block": (
                "utils/vision_transformer.html#block",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.Block.__init__": (
                "utils/vision_transformer.html#block.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.Block.forward": (
                "utils/vision_transformer.html#block.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.Embeddings": (
                "utils/vision_transformer.html#embeddings",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.Embeddings.__init__": (
                "utils/vision_transformer.html#embeddings.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.Embeddings.forward": (
                "utils/vision_transformer.html#embeddings.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.Encoder": (
                "utils/vision_transformer.html#encoder",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.Encoder.__init__": (
                "utils/vision_transformer.html#encoder.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.Encoder.forward": (
                "utils/vision_transformer.html#encoder.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.GELU": (
                "utils/vision_transformer.html#gelu",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.GELU.forward": (
                "utils/vision_transformer.html#gelu.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.MLP": (
                "utils/vision_transformer.html#mlp",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.MLP.__init__": (
                "utils/vision_transformer.html#mlp.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.MLP.forward": (
                "utils/vision_transformer.html#mlp.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.MultiHeadAttention": (
                "utils/vision_transformer.html#multiheadattention",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.MultiHeadAttention.__init__": (
                "utils/vision_transformer.html#multiheadattention.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.MultiHeadAttention.forward": (
                "utils/vision_transformer.html#multiheadattention.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.PatchEmbeddings": (
                "utils/vision_transformer.html#patchembeddings",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.PatchEmbeddings.__init__": (
                "utils/vision_transformer.html#patchembeddings.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.PatchEmbeddings.forward": (
                "utils/vision_transformer.html#patchembeddings.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.VisionTransformerClassifier": (
                "utils/vision_transformer.html#visiontransformerclassifier",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.VisionTransformerClassifier.__init__": (
                "utils/vision_transformer.html#visiontransformerclassifier.__init__",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.VisionTransformerClassifier._init_weights": (
                "utils/vision_transformer.html#visiontransformerclassifier._init_weights",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.VisionTransformerClassifier.forward": (
                "utils/vision_transformer.html#visiontransformerclassifier.forward",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vision_transformer.VisionTransformerConfig": (
                "utils/vision_transformer.html#visiontransformerconfig",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vision_transformer.py",
            ),
        },
        "build_a_text_to_image_generator_from_scratch_companion.utils.vqgan": {
            "build_a_text_to_image_generator_from_scratch_companion.utils.vqgan.VQGANLike": (
                "utils/vqgan.html#vqganlike",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vqgan.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vqgan._download_file": (
                "utils/vqgan.html#_download_file",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vqgan.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vqgan.download_vqgan_assets": (
                "utils/vqgan.html#download_vqgan_assets",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vqgan.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vqgan.image_to_sequence": (
                "utils/vqgan.html#image_to_sequence",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vqgan.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vqgan.load_model": (
                "utils/vqgan.html#load_model",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vqgan.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vqgan.process_image": (
                "utils/vqgan.html#process_image",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vqgan.py",
            ),
            "build_a_text_to_image_generator_from_scratch_companion.utils.vqgan.sequence_to_image": (
                "utils/vqgan.html#sequence_to_image",
                "build_a_text_to_image_generator_from_scratch_companion/utils/vqgan.py",
            ),
        },
    },
}
